### ISSUE TITLE
Add the repology badge to the site

### ISSUE THREAD

**Issue by XVilka** [latex3/latex3.github.io#1]
To show available versions of LaTeX/TeXLive in different distributions: https://repology.org/metapackage/texlive/versions

[![Packaging status](https://repology.org/badge/vertical-allrepos/texlive.svg)](https://repology.org/metapackage/texlive)

**Comment by josephwright** [comment]
I don't see what this really means: release LaTeX is on CTAN and (almost always) in current TeX Live from TUG.

**Comment by josephwright** [comment]
BTW, 'TeX Live' version doesn't really map to 'LaTeX kernel version', other than we tend to avoid doing releases in the freeze period (or in very controlled ways if we do).

**Comment by XVilka** [comment]
Yes, but most of the distributions use TeX Live packaged (and usually separated to individual subpackages). With this badge/link, it is easier to get the picture where LaTeX and other TeX infrastructure are old and where are updated.

**Comment by FrankMittelbach** [comment]
@XVilka true, but but what exactly is the gain for the user? he or she will not change the Linux distribution to get a newer LaTeX installation and in fact there is not need for that as for a long time it is fairly trivial to update TL on any platform. What I see being useful is to telling people more strongly that on Linux they may have to do a TL install even if there is an existing package already.

**Comment by XVilka** [comment]
They can poke the maintainers, usually, this is exactly what happens.

**Comment by davidcarlisle** [comment]
I think we should not add this. Already we have to be careful to explain that we do not distribute or maintain the tex executable, and do not manage ctan or texlive repositories.  Having a link to version numbers of texlive when we have no control or input into packaging texlive would I think add to that confusion not reduce it. You could run the current latex 2018-04-01 release on _any_ of those texlive versions, so the version of texlive isn't directly related to the latex code as developed on this site.

**Comment by davidcarlisle** [comment]
@FrankMittelbach  yes, exactly.

**Comment by FrankMittelbach** [comment]
30d5572f9aba5d3cdff24102325c63bdf668de85
