### ISSUE TITLE
Update description, links, and pdfs for docs `usrguide` and `clsguide`

### ISSUE THREAD

**Issue by muzimuzhi** [latex3/latex3.github.io#11]
The page https://www.latex-project.org/help/documentation/ still mentions `usrguide.pdf` and `usrguide3.pdf`, but now they are called `usrguide-historic.pdf` and `usrguide.pdf`, respectively.
https://github.com/latex3/latex3.github.io/blob/b2382cdb5eadd0d2a44f7fa4e40702a6f0afb695/help/documentation/index.md?plain=1#L60-L72

LaTeX2e now also provides `clsguide-historic.pdf` and `clsguide.pdf`, which are not reflected on page https://www.latex-project.org/help/documentation/.

Script needs an update too
https://github.com/latex3/latex3.github.io/blob/b2382cdb5eadd0d2a44f7fa4e40702a6f0afb695/_notes/generate-docs-for-website.sh#L24-L27

**Comment by muzimuzhi** [comment]
> ..., but now they are called `usrguide-historic.pdf` and `usrguide.pdf`, respectively.

This happened in LaTeX2e 2022-11-01, see https://github.com/latex3/latex2e/commit/28422122c1fe252b5584b1f2617f8037ea3203d4. The similar change for `clsguide` happened in the just-released LaTeX2e 2023-06-01, see https://github.com/latex3/latex2e/commit/ae2dfcf8a58ca3bb76e586e3afb13fb15963f2c1.

**Comment by FrankMittelbach** [comment]
took me a while to rediscover this one ...
